const products = [
  {
    id: "p1",
    name: "Stylish T-Shirt",
    price: 2499.99,
    category: "Fashion",
    image: "Shirt.jpg",
    description: "The Gildan Ultra Cotton T-shirt is crafted from a durable 6.0 oz. per sq. yd. fabric made with 100% cotton, delivering classic comfort that lasts. This preshrunk jersey knit tee features a taped neck and shoulders for added durability and a seamless double-needle collar for a smooth fit. Available in a wide range of colors, it's the perfect blend of comfort, style, and long-lasting quality—ideal for everyday wear or standout looks.",
  },
  {
    id: "p2",
    name: "Wireless Headphones",
    price: 3499.99,
    category: "Electronics",
    image: "headphone.jpg",
    description: "Experience high-quality sound with advanced noise cancellation for immersive music listening. Whether you're at home or on the go, enjoy crystal-clear audio and deep bass without distractions. Designed for comfort and performance, these headphones deliver the ultimate sound experience every time you press play",
  },
  {
    id: "p3",
    name: "Ceramic Vase",
    price: 1499.0,
    category: "Home & Living",
    image: "istockphoto-1300939276-612x612.jpg",
    description: "This elegant vase adds a touch of sophistication and charm to your living room decor. Crafted with a sleek design and timeless appeal, it perfectly complements modern or classic interiors. Display it with fresh flowers or as a standalone piece to enhance the beauty and warmth of your space.",
  },
  {
    id: "p4",
    name: "Natural Lip Balm",
    price: 999.99,
    category: "Beauty",
    image: "make-homemade-natural-organic-ingredients-260nw-1881057844.webp",
    description: "This hydrating and organic lip balm is made with natural ingredients to nourish and protect your lips. Its gentle formula soothes dryness, locks in moisture, and leaves a smooth, soft finish. Perfect for daily use, it provides long-lasting care with a refreshing feel—ideal for healthy, naturally beautiful lips.",
  },
  {
    id: "p5",
    name: "Denim Jeans",
    price: 1299.99,
    category: "Fashion",
    image: "jeans.jpg",
    description: "These classic fit denim jeans are crafted from durable, high-quality fabric for long-lasting wear and comfort. Featuring a timeless design with a relaxed silhouette, they’re perfect for everyday use. Pair them with any top for a versatile look that never goes out of style—reliable, stylish, and built to last.",
  },
  {
    id: "p6",
    name: "Smartphone",
    price: 149999.99,
    category: "Electronics",
    image: "photo_2025-06-29_20-25-57.jpg",
    description: "Experience the latest model equipped with all the features you need for modern living. Designed for performance and convenience, it offers advanced functionality, sleek style, and user-friendly controls. Whether for work or play, this cutting-edge device delivers reliability, speed, and smart technology in one powerful, all-in-one package.",
  },
  {
    id: "p7",
    name: "Scented Candle",
    price: 199.99,
    category: "Home & Living",
    image: "candle.jpg",
    description: "Create a soothing atmosphere with this relaxing aroma, perfect for brightening up your home. Infused with calming scents, it helps reduce stress and uplift your mood. Whether used in the living room, bedroom, or workspace, its gentle fragrance brings warmth, comfort, and a refreshing touch to any space.",
  },
  {
    id: "p8",
    name: "Moisturizer Cream",
    price: 599.99,
    category: "Beauty",
    image: "BEST-FACIAL-MOISTURIZERS-SUB-2048px-1830.webp",
    description: "Keeps your skin deeply hydrated and soft throughout the day. This moisturizer cream nourishes and restores moisture balance, leaving skin smooth and refreshed. Perfect for daily skincare routines, it helps maintain a healthy glow while protecting against dryness and environmental stressors for all skin types.",
  },
  {
    id: "p9",
    name: "Black Hoodie",
    price: 2999.99,
    category: "Fashion",
    image: "black-hoodie.png",
    description: "Stay cozy and stylish with this comfortable black hoodie made from organic cotton. Its soft fabric ensures warmth and breathability, perfect for casual outings or lounging at home. Designed with trendy details, this hoodie combines eco-friendly materials with everyday comfort for a versatile wardrobe essential.",
  },
  {
    id: "p10",
    name: "Winter Coat",
    price: 2999.99,
    category: "Fashion",
    image: "Winter-Coat.png",
    description: "This winter coat offers both warmth and style with its premium organic cotton fabric. Designed for comfort during cold days, it features a trendy look that complements any outfit. Ideal for chilly weather, the coat keeps you cozy while maintaining a modern and fashionable silhouette.",
  },
  {
    id: "p11",
    name: "High Heel",
    price: 1999.99,
    category: "Fashion",
    image: "women shoes.jpg",
    description: "Step out confidently in these comfortable and trendy high heels crafted from organic cotton materials. Designed to combine elegance with comfort, they enhance your style while supporting your feet. Perfect for formal events or everyday wear, these heels add a chic touch to any outfit.",
  },
  {
    id: "p12",
    name: "Modern Bed Interior",
    price: 9999.99,
    category: "Home & Living",
    image: "Modern Bed Interior.jpg",
    description: "Enhance your bedroom with this modern bed crafted from organic wood, blending comfort and contemporary design. Its sturdy construction ensures durability, while the sleek lines create a stylish focal point. Perfect for a cozy and elegant sleeping space that combines nature-inspired elements with modern aesthetics.",
  },
  {
    id: "p13",
    name: "ottoman empire furniture with classic ornaments",
    price: 5999.99,
    category: "Home & Living",
    image: "ottoman empire furniture with classic ornaments.jpg",
    description: "This exquisite Ottoman Empire furniture piece features classic ornaments and is made from quality organic wood. Combining historical elegance with modern comfort, it brings timeless charm to your home. Perfect for adding a sophisticated and cultural touch to your living space with durable craftsmanship.",
  },
  {
    id: "p14",
    name: "French Furniture With classical Ornaments",
    price: 3999.99,
    category: "Home & Living",
    image: "French Furniture With classical Ornaments.jpg",
    description: "Add a touch of elegance with French furniture adorned with classical ornaments. Crafted from organic wood, this piece blends timeless design with modern comfort. Its intricate details and quality materials make it an ideal choice for enhancing the sophistication and style of your home interior.",
  },
  {
    id: "p15",
    name: "High Performance GPU with Cyberpunk Coolers",
    price: 19999.99,
    category: "Electronics",
    image: "High Performance GPU with Cyberpunk Coolers.jpg",
    description: "Experience powerful graphics performance with this high-quality GPU featuring cyberpunk-inspired coolers. Designed for demanding PC tasks, it delivers smooth gameplay and efficient cooling. Perfect for gamers and professionals seeking cutting-edge technology with a bold aesthetic and reliable strength.",
  },
  {
    id: "p17",
    name: "Black Power Bank 18W",
    price: 3499.99,
    category: "Electronics",
    image: "Black Power Bank 18W.jpg",
    description: "Stay charged on the go with this sleek black power bank delivering 18W fast charging. Made with sustainable materials, it offers reliable and efficient power for your phone and devices. Compact and durable, it’s the perfect travel companion to keep you connected anytime, anywhere.",
  },
  {
    id: "p18",
    name: "Apple MacBook Air (M4)",
    price: 199999.99,
    category: "Electronics",
    image: "laptop.jpg",
    description: "Discover high performance with the Apple MacBook Air (M4), engineered for speed and efficiency. Its lightweight design combines portability with powerful computing, ideal for work or creativity. Featuring the latest technology, it ensures smooth multitasking and long battery life in a sleek, modern package.",
  },
  {
    id: "p19",
    name: "Vibrant Colors of Eyeshadow",
    price: 3999.99,
    category: "Beauty",
    image: "Vibrant Colors of Eyeshadow.jpg",
    description: "Brighten your look with these vibrant eyeshadows that keep your eyes colorful and hydrated all day. The smooth formula glides on effortlessly, providing rich pigmentation and lasting wear. Perfect for creating bold or subtle eye makeup, enhancing your natural beauty with a splash of vivid color.",
  },
  {
    id: "p20",
    name: "Pink Nail polish with Golden Glitter",
    price: 3999.99,
    category: "Beauty",
    image: "Pink Nail polish with Golden Glitter.jpg",
    description: "Add sparkle to your nails with this pink nail polish featuring golden glitter for a dazzling finish. Designed to keep your nails shiny and colorful all day, it offers long-lasting wear and a smooth application. Perfect for adding glamour and a festive touch to your manicure.",
  },
  {
    id: "p21",
    name: "Crimson LipStick",
    price: 3999.99,
    category: "Beauty",
    image: "Crimson LipStick.jpg",
    description: "Enhance your lips with this crimson lipstick that keeps them soft and vividly red all day. Its moisturizing formula provides rich color and smooth application, ensuring a bold, elegant look. Perfect for any occasion, it combines lasting hydration with a stunning finish to highlight your smile.",
  },
];
